// modelSchema.js
export const modelSchemas = {
  Category: [
    { name: "title", type: "string", required: true },
    { name: "description", type: "string", required: false },
  ],
  Unit: [
    { name: "title", type: "string", required: true },
    { name: "abbreviation", type: "string", required: true },
  ],
  Brand: [
    { name: "title", type: "string", required: true },
  ],
  Warehouse: [
    { name: "title", type: "string", required: true },
    { name: "location", type: "string", required: false },
    { name: "description", type: "string", required: false },
    { name: "warehouseType", type: "string", required: true },
  ],
  Supplier: [
    { name: "title", type: "string", required: true },
    { name: "phone", type: "string", required: false },
    { name: "email", type: "string", required: false },
    { name: "address", type: "string", required: false },
    { name: "contactPerson", type: "string", required: false },
    { name: "supplierCode", type: "string", required: true },
    { name: "paymentTerms", type: "string", required: false },
    { name: "taxID", type: "string", required: false },
    { name: "notes", type: "string", required: false },
  ],
  Item: [
    { name: "title", type: "string", required: true },
    { name: "description", type: "string", required: false },
    { name: "categoryId", type: "string", required: true,ref: "category" },
    { name: "sku", type: "string", required: true },
    { name: "barcode", type: "string", required: false },
    { name: "quantity", type: "number", required: true },
    { name: "unitId", type: "string", required: true,ref: "unit"  },
    { name: "brandId", type: "string", required: true,ref: "brand"  },
    { name: "warehouseId", type: "string", required: true,ref: "warehouse"  },
    { name: "sellingPrice", type: "number", required: true },
    { name: "buyingPrice", type: "number", required: true },
    { name: "supplierId", type: "string", required: true,ref: "supplier"  },
    { name: "reOrderPoint", type: "number", required: true },
    { name: "location", type: "string", required: false },
    { name: "imageUrl", type: "string", required: false },
    { name: "weight", type: "number", required: false },
    { name: "dimensions", type: "string", required: false },
    { name: "taxRate", type: "number", required: true },
    { name: "notes", type: "string", required: false },
  ],
};
